name: moa_customers_client
version: 2.1.0
description: A Dart client for MyOrderApp customer HTTP API
homepage: https://api.myorderapp.dev/customers/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: '^5.2.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
